additionalProperties:
  aspnetCoreVersion: 6.0
  nullableReferenceTypes: true
  buildTarget: library
  useSwashbuckle: true
  packageName: PxWeb.Api2.Server
  packageTitle: PxWeb.Api2.Server
  packageDescription: Server library for PxWeb API 2.0
  licenseName: Apache-2.0
  packageAuthors: SCB & SSB

