#!/usr/bin/env bash
#
# Generated by: https://openapi-generator.tech
#

dotnet restore src/PxWeb.Api2.Server/ && \
    dotnet build src/PxWeb.Api2.Server/ && \
    echo "Now, run the following to start the project: dotnet run -p src/PxWeb.Api2.Server/PxWeb.Api2.Server.csproj --launch-profile web"
