openapi: 3.0.3
info:
  title: PxApi
  version: '1.0'
  description: "This api is part of the PX-family.\r\n Q: Should the tables and the navigate endpoint have different backends(Lucene vs sql)?"
paths:
  /topictree:
    get:
      tags:
        - TopicTree
      summary: "This has an include part, in stead of nested elements. \r\n The menutree starts here. Gets the MenuItem at the root node"
      operationId: GetTopics
      parameters:
        - $ref: '#/components/parameters/levelsParam'
        - $ref: '#/components/parameters/langParam'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseMenuItem'
        '429':
          $ref: '#/components/responses/ErrorResponse429'
  /topictree/{id}:
    get:
      tags:
        - TopicTree
      summary: Gets the MenuItem for the node with the given id.
      operationId: GetTopicsById
      parameters:
        - $ref: '#/components/parameters/levelsParam'
        - $ref: '#/components/parameters/menuIdParam'
        - $ref: '#/components/parameters/langParam'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseMenuItem'
components:
  parameters:
    langParam:
      name: lang
      in: query
      description: The language if the default is not what you want.
      required: false
      schema:
        type: string
      examples:
        X1:
          value: en
          summary: For english
        X2:
          value: dk
          summary: For danish
    menuIdParam:
      name: id
      in: path
      description: The menu-id of the desired node
      required: true
      schema:
        type: string
    levelsParam:
      name: levels
      in: query
      description: Number of levels that are fetched in the response. Minimun 0, which will fetch all levels in the menutree.
      schema:
        type: integer
        format: int32
        default: 1
        minimum: 0
  schemas:
    BaseResponse:
      type: object
      description: Common properties for all responses. Abstract class.
      properties:
        error:
          type: string
          description: Errors will come here
          nullable: true
        info:
          type: string
          description: Messages on planed maintainence willl come here.
          nullable: true
      example:
        error: The id cant be found
        info: Closed on mondays
    ResponseMenuItem:
      allOf:
        - $ref: '#/components/schemas/BaseResponse'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/BaseMenuItem'
      description: This holds information about the menutree of the api.
      example:
        data:
          id: ''
          menuItemType: folder
          label: null
          sortOrder: 42
          links: null
          folderContent:
            - id: al
              menuItemType: folder
              label: Folder 1
              sortOrder: 43
              links:
                - rel: included_data
                  href: '#/included/al'
            - id: AKUAarNY
              menuItemType: table
              label: '05111: Table in root folder'
              sortOrder: 44
              links:
                - rel: tables
                  href: https://my-site.com/api/v2/tables/AKUAarNY
          included:
            - id: al
              menuItemType: folder
              label: Folder 1
              sortOrder: 43
              links: null
              folderContent:
                - id: al_al03
                  menuItemType: closed-folder
                  label: Folder 1 1
                  sortOrder: 45
                  links:
                    - rel: data
                      href: https://localhost:7067/navigate/treealt2/al_al03
                - id: ForstgenArbNye
                  menuItemType: table
                  label: '07116: Table in Folder 1'
                  sortOrder: 46
                  links:
                    - rel: metadata
                      href: https://my-site.com/api/v2/tables/ForstgenArbNye
                - id: al_al04
                  menuItemType: closed-folder
                  label: Folder 1 2
                  sortOrder: 47
                  links:
                    - rel: data
                      href: https://localhost:7067/navigate/treealt2/al_al04
        error: null
        info: null
    ResponseToDo:
      allOf:
        - $ref: '#/components/schemas/BaseResponse'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/ToDo'
    Link:
      type: object
      properties:
        rel:
          type: string
          nullable: true
        href:
          type: string
          nullable: true
      additionalProperties: false
    MenuItem:
      type: object
      properties:
        id:
          type: string
          nullable: true
        menuItemType:
          type: string
          nullable: true
          description: One of heading, table or folder
        label:
          type: string
          nullable: true
          description: Display text
        description:
          type: string
          nullable: true
          description: Longer text describing menu item.
        tags:
          type: array
          items:
            type: string
            description: tag for menu item
          nullable: true
        sortOrder:
          type: integer
          format: int32
        links:
          type: array
          items:
            $ref: '#/components/schemas/Link'
          description: Not for Heading
          nullable: true
        updated:
          type: string
          description: For menuItemType "table"
          format: date-time
          nullable: true
        folderContent:
          type: array
          items:
            $ref: '#/components/schemas/MenuItem'
          nullable: true
        included:
          type: array
          items:
            $ref: '#/components/schemas/MenuItem'
          nullable: true
          description: Holds the prefetched items.
        category:
          type: string
          description: Mostly for internal use. Which category table belongs to. internal, official, private or section. I, O, P, S
          default: official
          enum:
          - internal
          - official
          - private
          - section     
      additionalProperties: false
    Problem:
      type: object
      properties:
        type:
          type: string
          format: uri
          description: |
            An absolute URI that identifies the problem type.  When dereferenced,
            it SHOULD provide human-readable documentation for the problem type
            (e.g., using HTML).
          default: about:blank
          example: https://zalando.github.io/problem/constraint-violation
        title:
          type: string
          description: |
            A short, summary of the problem type. Written in english and readable
            for engineers (usually not suited for non technical stakeholders and
            not localized); example: Service Unavailable
        status:
          type: integer
          format: int32
          description: |
            The HTTP status code generated by the origin server for this occurrence
            of the problem.
          minimum: 100
          maximum: 600
          exclusiveMaximum: true
          example: 503
        detail:
          type: string
          description: |
            A human readable explanation specific to this occurrence of the
            problem.
          example: Connection to database timed out
        instance:
          type: string
          format: uri
          description: |
            An absolute URI that identifies the specific occurrence of the problem.
            It may or may not yield further information if dereferenced.
    ToDo:
      type: object
      properties:
        something:
          type: string
          nullable: true
      additionalProperties: false
    BaseMenuItem:
      type: object
      properties:
        id:
          type: string
          nullable: true
        menuItemType:
          type: string
          nullable: true
          description: One of heading, table or folder
        label:
          type: string
          nullable: true
          description: Display text
        description:
          type: string
          nullable: true
          description: Longer text describing menu item.
        sortOrder:
          type: string
          description: Sort order.
      discriminator:
         propertyName:  menuItemType
         mapping:
           table: '#/components/schemas/TableMenuItem'
           heading: '#/components/schemas/HeadingMenuItem'
           folder: '#/components/schemas/FolderItem'
      anyOf:
        - $ref: '#/components/schemas/TableMenuItem'
        - $ref: '#/components/schemas/HeadingMenuItem'
        - $ref: '#/components/schemas/FolderItem'
    TableMenuItem:
      allOf:
        - $ref: '#/components/schemas/BaseMenuItem'
        - type: object
          description: Table menu item
          properties:
            updated:
              type: string
              description: For menuItemType "table"
              format: date-time
              nullable: true
            tags:
              type: array
              items:
                type: string
                description: tag for menu item
              nullable: true
            category:
              type: string
              description: Mostly for internal use. Which category table belongs to. internal, official, private or section. I, O, P, S
              default: official
              enum:
              - internal
              - official
              - private
              - section     
            links:
              type: array
              items:
                $ref: '#/components/schemas/Link'
              description: Not for Heading
              nullable: true
    FolderItem:
      allOf:
        - $ref: '#/components/schemas/BaseMenuItem'
        - type: object
          description: Folder item
          properties:
            tags:
              type: array
              items:
                type: string
                description: tag for menu item
              nullable: true
            folderContent:
              type: array
              items:
                $ref: '#/components/schemas/BaseMenuItem'
              nullable: true
            included:
              type: array
              items:
                $ref: '#/components/schemas/BaseMenuItem'
              nullable: true
              description: Holds the prefetched items.
            links:
              type: array
              items:
                $ref: '#/components/schemas/Link'
              description: Not for Heading
              nullable: true
    HeadingMenuItem:
      allOf:
        - $ref: '#/components/schemas/BaseMenuItem'
        - type: object
          description: Pedaled Vehicle
          properties:
             maxSpeed:
               description: The top speed in kilometers per hour rounded to the nearest integer.
               type: integer
               example: 83         
  responses:
    ErrorResponse429:
      description: Error respsone for 429
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
          example:
            title: Too many requests
            status: 429
            detail: You have reach the threshold for request limiting. 30 request per minute.
tags:
  - name: TopicTree
    description: Endpoints for the menutree.