openapi: '3.0.2'
info:
  title: PxApi
  version: '2.0'
servers:
  - url: https://api.server.test/api/v2
paths:
  /navigation:
      get:
        tags:
          - Navigation
        summary: Browse the database structure
        operationId: GetNavigationRoot
        parameters:
          - $ref: '#/components/parameters/language'
        responses:
          '200':
            description: Success
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Folder'
                examples:
                  NavigateRoot:
                    $ref: '#/components/examples/navigation-root'
          '429':
            $ref: '#/components/responses/ErrorResponse429'
  /navigation/{id}:
    get:
      tags:
        - Navigation
      summary: Gets navigation item with the given id.
      operationId: GetNavigationById
      parameters:
        - $ref: '#/components/parameters/id'
        - $ref: '#/components/parameters/language'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Folder'
              examples:
                  Navigation-BE:
                    $ref: '#/components/examples/navigation-be'
  /tables:
    get:
      tags:
        - Table
      summary: Endpoint for listing tables
      operationId: ListAllTables
      parameters:
        - $ref: '#/components/parameters/query'
        - $ref: '#/components/parameters/pastDays'
        - $ref: '#/components/parameters/include_discontinued'
        - $ref: '#/components/parameters/pageNumber'
        - $ref: '#/components/parameters/pageSize'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TablesResponse'
              examples:
                  tables:
                    $ref: '#/components/examples/tablesResponse'
  /tables/{id}:
    get:
      tags:
        - Table
      summary: Endpoint to get table by {id}
      operationId: GetTableById
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Table'
components:
  parameters:
    language:
      name: lang
      in: query
      description: The language if the default is not what you want.
      required: false
      schema:
        type: string
        nullable: true
      examples:
        X1:
          value: en
          summary: For english
        X2:
          value: dk
          summary: For danish
    id:
      name: id
      in: path
      description: Id
      required: true
      schema:
        type: string
    query:
      name: query
      in: query
      description: Selects only tables that that matches a criteria which is specified by the search parameter.
      required: false
      schema:
        type: string
      examples:
        X1:
          value: befolkning
          summary: Search for tables with name `befolkning`
    pastDays:
      name: pastDays
      in: query
      description: Selects only tables that was updated from the time of execution going back number of days stated by the parameter pastDays. Valid values for past days are integers between 1 and ?
      required: false
      schema:
        type: integer
        minimum: 1
      examples:
        X1:
          value: 5
          summary: Search for tables which has been updated in the last 5 days
    include_discontinued:
      name: includeDiscontinued
      in: query
      description: Decides if discontinued tables are included in response.
      required: false
      schema:
        type: boolean
        default: false
        example: false
    pageNumber:
      name: pageNumber
      in: query
      description: "Pagination: Decides which page number to return"
      required: false
      schema:
        type: integer
        default: 1
    pageSize:
      name: pageSize
      in: query
      description: "Pagination: Decides how many tables per page"
      required: false
      schema:
        type: integer
        #Default value depends on site?
  schemas:
    FolderContentItem:
      type: object
      description: Navigation item.
      properties:
        id:
          type: string
          nullable: true
          #nullable = true beacause root is empty
        objectType:
          type: string
          nullable: false
          description: One of heading, table, folder or folder-information
        label:
          type: string
          nullable: true
          description: Display text
        description:
          type: string
          nullable: true
          description: Longer text describing node. If no longer text exist, same as label
    Folder:
      type: object
      description: Folder item
      properties:
        id:
          type: string
          nullable: true
          #nullable = true beacause root is empty
        objectType:
          type: string
          nullable: false
          description: One of heading, table, folder or folder-information
        label:
          type: string
          nullable: true
          description: Display text
        description:
          type: string
          nullable: true
          description: Longer text describing node.
        tags:
          type: array
          items:
            type: string
            description: tag for folder
          nullable: true
        folderContents:
          type: array
          items:
            $ref: '#/components/schemas/FolderContentItem'
          nullable: true
        links:
          type: array
          items:
            $ref: '#/components/schemas/Link'
          description: Links to ...
          nullable: true
    FolderInformation:
      allOf:
        - $ref: '#/components/schemas/FolderContentItem'
        - type: object
          description: Folder information item
          properties:
            tags:
              type: array
              items:
                type: string
                description: tag for folder
              nullable: true
            links:
              type: array
              items:
                $ref: '#/components/schemas/Link'
              description: Links to ...
              nullable: true
    Heading:
      allOf:
        - $ref: '#/components/schemas/FolderContentItem'
        - type: object
          description: Heading item
    Table:
      allOf:
        - $ref: '#/components/schemas/FolderContentItem'
        - type: object
          description: Table item
          properties:
            tags:
              type: array
              items:
                type: string
                description: tag for table
              nullable: true
            updated:
              type: string
              description: For treeNodeType "table"
              format: date-time
              nullable: true
            category:
              type: string
              description: Mostly for internal use. Which category table belongs to. internal, official, private or section. I, O, P, S
              default: official
              enum:
              - internal
              - official
              - private
              - section
            links:
              type: array
              items:
                $ref: '#/components/schemas/Link'
              description: Links to ...
              nullable: true
            variablesName:
              type: array
              description: List of varibles name
              items:
                type: string
            firstPeriod:
              type: string
              description: First period
              example: 2017
            lastPeriod:
              type: string
              description: Last period
              example: 2022
            discontinued:
              type: boolean
    TablesResponse:
      allOf:
        - type: object
          properties:
            tables:
              type: array
              items:
                 $ref: '#/components/schemas/Table'
        - $ref: '#/components/schemas/Page'
        - type: object
          properties:
            links:
              type: array
              items:
                 $ref: '#/components/schemas/Link'
    Page:
      type: object
      properties:
        page:
          type: object
          properties:
            pageNumber:
              type: integer
              format: int32
            pageSize:
              type: integer
              format: int32
              example: 33
            totalElements:
              type: integer
              format: int32
            totalPages:
              type: integer
              format: int32
    Link:
      type: object
      properties:
        rel:
          type: string
          nullable: false
        href:
          type: string
          nullable: false
      additionalProperties: false
      required:
        - rel
        - href
    Problem:
      type: object
      properties:
        type:
          type: string
          format: uri
          description: |
            An absolute URI that identifies the problem type.  When dereferenced,
            it SHOULD provide human-readable documentation for the problem type
            (e.g., using HTML).
          default: about:blank
          example: https://zalando.github.io/problem/constraint-violation
        title:
          type: string
          description: |
            A short, summary of the problem type. Written in english and readable
            for engineers (usually not suited for non technical stakeholders and
            not localized); example: Service Unavailable
        status:
          type: integer
          format: int32
          description: |
            The HTTP status code generated by the origin server for this occurrence
            of the problem.
          minimum: 100
          maximum: 600
          exclusiveMaximum: true
          example: 503
        detail:
          type: string
          description: |
            A human readable explanation specific to this occurrence of the
            problem.
          example: Connection to database timed out
        instance:
          type: string
          format: uri
          description: |
            An absolute URI that identifies the specific occurrence of the problem.
            It may or may not yield further information if dereferenced.
  responses:
    ErrorResponse429:
      description: Error respsone for 429
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
            #Reference: 
            # https://dzone.com/articles/rest-api-error-handling-problem-details-response
            # https://datatracker.ietf.org/doc/html/rfc7807
            # https://nordicapis.com/best-practices-api-error-handling/
          example:
            title: Too many requests
            status: 429
            detail: You have reach the threshold for request limiting. 30 request per minute.
  examples:  
    navigation-root:
      description: Example for 200 response for navigation endpoint
      value:
        id: 
        objectType: folder
        label: 
        description: 
        links:
        - rel: self
          href: https://my-site.com/api/v2/navigation
        folderContents:
        - id: JO
          objectType: folder
          label: Agriculture, forestry and fishery
          description: Animals, economy, employment, production, and more.
          links:
          - rel: self
            href: https://my-site.com/api/v2/navigation/JO
        - id: NV
          objectType: folder
          label: Financial markets
          description: Assets, banks, insurance companies, liabilities, shares, and more.
          links:
          - rel: self
            href: https://my-site.com/api/v2/navigation/NV

    navigation-be:
      description: Example for 200 response for navigation endpoint
      value:
        id: BE0101
        objectType: folder
        label: Balance statistics
        description: Balance statistics
        links:
        - rel: self
          href: https://my-site.com/api/v2/navigation/BE0101
        folderContents:
        - id: "01"
          objectType: folder-information
          label: Annual statistics
          description: Annual statistics
          links:
          - rel: folder
            href: https://my-site.com/api/v2/navigation/01
        - id: BEH1
          objectType: heading
          label: I am heading
          description: I am heading
        - id: TAB0001
          objectType: table
          label: Corporations Financial Assets and Liabilities. Quarterly 1998K2 - 2021K4
          description: Corporations Financial Assets and Liabilities by item. Quarterly 1998K2 - 2021K4 [2022-03-11]
          updated: 2017-09-08T19:01:55.714942+03:00
          categoy: 'O'
          tags: 
          - Money
          - Gold
          links:
          - rel: self
            href: https://my-site.com/api/v2/tables/TAB0001
          - rel: metadata
            href: https://my-site.com/api/v2/tables/TAB0001/metadata
          - rel: data
            href: https://my-site.com/api/v2/tables/TAB0001/data
          variablesName:
            - observations
            - region
            - marital status
            - age
          firstPeriod: 1998K2
          lastPeriod: 2021K4
          discontinued: false
    tablesResponse:
      description: List all tables with pagination
      value:
        tables: 
          - id: TAB0001
            objectType: table
            label: Population. Year 1968 - 2021
            description: Population by region, marital status, age and sex. Year 1968 - 2021
            updated: 2017-09-08T19:01:55.714942+03:00
            categoy: 'O'
            tags: []
            links:
            - rel: self
              href: https://my-site.com/api/v2/tables/TAB0001
            - rel: metadata
              href: https://my-site.com/api/v2/tables/TAB0001/metadata
            - rel: data
              href: https://my-site.com/api/v2/tables/TAB0001/data
            variablesName:
              - observations
              - region
              - marital status
              - age
            firstPeriod: 1968
            lastPeriod: 2021
            discontinued: false
          - id: TAB0001
            objectType: table
            label: Tabell A
            description: Folkmängd, in- och utvanding, medellivslängd, namn, prognoser mm
            updated: 2017-09-08T19:01:55.714942+03:00
            categoy: 'O'
            tags: []
            links:
            - rel: self
              href: https://my-site.com/api/v2/tables/TAB0001
            - rel: metadata
              href: https://my-site.com/api/v2/tables/TAB0001/metadata
            - rel: data
              href: https://my-site.com/api/v2/tables/TAB0001/data
            variablesName:
              - observations
              - region
              - marital status
              - age
            firstPeriod: 2017
            lastPeriod: 2022
            discontinued: false
        page:
          pageNumber: 10
          pageSize: 100
          totalElements: 7000
          totalPages: 70
        links:
          - rel: self
            href: https://my-site.com/api/v2/tables/?pageNumber=10
          - rel: first
            href: https://my-site.com/api/v2/tables/?pageNumber=1
          - rel: last
            href: https://my-site.com/api/v2/tables/?pageNumber=70
          - rel: next
            href: https://my-site.com/api/v2/tables/?pageNumber=11
          - rel: prev
            href: https://my-site.com/api/v2/tables/?pageNumber=9  
