/* tslint:disable */
/* eslint-disable */
/**
 * PxApi
 * This api lets you do 2 things; Find a table(Navigation) and use a table (Table).  _Table below is added to show how tables can be described in yml._  **Table contains status code this API may return** | Status code    | Description      | Reason                      | | -------        | -----------      | ---------------------       | | 200            | Success          | The endpoint has delivered response for the request                      | | 400            | Bad request      | If the request is not valid | | 403            | Forbidden        | number of cells exceed the API limit | | 404            | Not found        | If the URL in request does not exist | | 429            | Too many request | Requests exceed the API time limit. Large queries should be run in sequence | | 50X            | Internal Server Error | The service might be down | 
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CodeListMetadata } from './CodeListMetadata';
import {
    CodeListMetadataFromJSON,
    CodeListMetadataFromJSONTyped,
    CodeListMetadataToJSON,
    CodeListMetadataToJSONTyped,
} from './CodeListMetadata';
import type { Link } from './Link';
import {
    LinkFromJSON,
    LinkFromJSONTyped,
    LinkToJSON,
    LinkToJSONTyped,
} from './Link';

/**
 * 
 * @export
 * @interface CodeListsResponse
 */
export interface CodeListsResponse {
    /**
     * The language code for the language used in this response
     * @type {string}
     * @memberof CodeListsResponse
     */
    language: string;
    /**
     * 
     * @type {Array<CodeListMetadata>}
     * @memberof CodeListsResponse
     */
    codeLists?: Array<CodeListMetadata>;
    /**
     * 
     * @type {Array<Link>}
     * @memberof CodeListsResponse
     */
    links?: Array<Link>;
}

/**
 * Check if a given object implements the CodeListsResponse interface.
 */
export function instanceOfCodeListsResponse(value: object): value is CodeListsResponse {
    if (!('language' in value) || value['language'] === undefined) return false;
    return true;
}

export function CodeListsResponseFromJSON(json: any): CodeListsResponse {
    return CodeListsResponseFromJSONTyped(json, false);
}

export function CodeListsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CodeListsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'language': json['language'],
        'codeLists': json['codeLists'] == null ? undefined : ((json['codeLists'] as Array<any>).map(CodeListMetadataFromJSON)),
        'links': json['links'] == null ? undefined : ((json['links'] as Array<any>).map(LinkFromJSON)),
    };
}

export function CodeListsResponseToJSON(json: any): CodeListsResponse {
    return CodeListsResponseToJSONTyped(json, false);
}

export function CodeListsResponseToJSONTyped(value?: CodeListsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'language': value['language'],
        'codeLists': value['codeLists'] == null ? undefined : ((value['codeLists'] as Array<any>).map(CodeListMetadataToJSON)),
        'links': value['links'] == null ? undefined : ((value['links'] as Array<any>).map(LinkToJSON)),
    };
}

