/* tslint:disable */
/* eslint-disable */
/**
 * PxApi
 * This api lets you do 2 things; Find a table(Navigation) and use a table (Table).  _Table below is added to show how tables can be described in yml._  **Table contains status code this API may return** | Status code    | Description      | Reason                      | | -------        | -----------      | ---------------------       | | 200            | Success          | The endpoint has delivered response for the request                      | | 400            | Bad request      | If the request is not valid | | 403            | Forbidden        | number of cells exceed the API limit | | 404            | Not found        | If the URL in request does not exist | | 429            | Too many request | Requests exceed the API time limit. Large queries should be run in sequence | | 50X            | Internal Server Error | The service might be down | 
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VariablePlacementType
 */
export interface VariablePlacementType {
    /**
     * List of variables that should be placed in the heading in the resulting data
     * @type {Array<string>}
     * @memberof VariablePlacementType
     */
    heading?: Array<string>;
    /**
     * List of variables that should be placed in the stub in the resulting data
     * @type {Array<string>}
     * @memberof VariablePlacementType
     */
    stub?: Array<string>;
}

/**
 * Check if a given object implements the VariablePlacementType interface.
 */
export function instanceOfVariablePlacementType(value: object): value is VariablePlacementType {
    return true;
}

export function VariablePlacementTypeFromJSON(json: any): VariablePlacementType {
    return VariablePlacementTypeFromJSONTyped(json, false);
}

export function VariablePlacementTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): VariablePlacementType {
    if (json == null) {
        return json;
    }
    return {
        
        'heading': json['heading'] == null ? undefined : json['heading'],
        'stub': json['stub'] == null ? undefined : json['stub'],
    };
}

export function VariablePlacementTypeToJSON(json: any): VariablePlacementType {
    return VariablePlacementTypeToJSONTyped(json, false);
}

export function VariablePlacementTypeToJSONTyped(value?: VariablePlacementType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'heading': value['heading'],
        'stub': value['stub'],
    };
}

