/* tslint:disable */
/* eslint-disable */
/**
 * PxApi
 * This api lets you do 2 things; Find a table(Navigation) and use a table (Table).  _Table below is added to show how tables can be described in yml._  **Table contains status code this API may return** | Status code    | Description      | Reason                      | | -------        | -----------      | ---------------------       | | 200            | Success          | The endpoint has delivered response for the request                      | | 400            | Bad request      | If the request is not valid | | 403            | Forbidden        | number of cells exceed the API limit | | 404            | Not found        | If the URL in request does not exist | | 429            | Too many request | Requests exceed the API time limit. Large queries should be run in sequence | | 50X            | Internal Server Error | The service might be down | 
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CodeListType } from './CodeListType';
import {
    CodeListTypeFromJSON,
    CodeListTypeFromJSONTyped,
    CodeListTypeToJSON,
    CodeListTypeToJSONTyped,
} from './CodeListType';
import type { ValueMap } from './ValueMap';
import {
    ValueMapFromJSON,
    ValueMapFromJSONTyped,
    ValueMapToJSON,
    ValueMapToJSONTyped,
} from './ValueMap';
import type { Link } from './Link';
import {
    LinkFromJSON,
    LinkFromJSONTyped,
    LinkToJSON,
    LinkToJSONTyped,
} from './Link';

/**
 * 
 * @export
 * @interface CodeListResponse
 */
export interface CodeListResponse {
    /**
     * The identiyer for the codelist
     * @type {string}
     * @memberof CodeListResponse
     */
    id: string;
    /**
     * The textual name  for the codelist.
     * @type {string}
     * @memberof CodeListResponse
     */
    label: string;
    /**
     * The language code for the language used in this response
     * @type {string}
     * @memberof CodeListResponse
     */
    language: string;
    /**
     * The languages that the codelist is available in
     * @type {Array<string>}
     * @memberof CodeListResponse
     */
    languages: Array<string>;
    /**
     * If the codelist is eliminatable
     * @type {boolean}
     * @memberof CodeListResponse
     */
    elimination?: boolean;
    /**
     * The value code that should be used for elimination. If not set the variable will be eliminated by summing up all values.
     * @type {string}
     * @memberof CodeListResponse
     */
    eliminationValueCode?: string;
    /**
     * 
     * @type {CodeListType}
     * @memberof CodeListResponse
     */
    type: CodeListType;
    /**
     * 
     * @type {Array<ValueMap>}
     * @memberof CodeListResponse
     */
    values: Array<ValueMap>;
    /**
     * 
     * @type {Array<Link>}
     * @memberof CodeListResponse
     */
    links: Array<Link>;
}



/**
 * Check if a given object implements the CodeListResponse interface.
 */
export function instanceOfCodeListResponse(value: object): value is CodeListResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('language' in value) || value['language'] === undefined) return false;
    if (!('languages' in value) || value['languages'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('values' in value) || value['values'] === undefined) return false;
    if (!('links' in value) || value['links'] === undefined) return false;
    return true;
}

export function CodeListResponseFromJSON(json: any): CodeListResponse {
    return CodeListResponseFromJSONTyped(json, false);
}

export function CodeListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CodeListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'label': json['label'],
        'language': json['language'],
        'languages': json['languages'],
        'elimination': json['elimination'] == null ? undefined : json['elimination'],
        'eliminationValueCode': json['eliminationValueCode'] == null ? undefined : json['eliminationValueCode'],
        'type': CodeListTypeFromJSON(json['type']),
        'values': ((json['values'] as Array<any>).map(ValueMapFromJSON)),
        'links': ((json['links'] as Array<any>).map(LinkFromJSON)),
    };
}

export function CodeListResponseToJSON(json: any): CodeListResponse {
    return CodeListResponseToJSONTyped(json, false);
}

export function CodeListResponseToJSONTyped(value?: CodeListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'label': value['label'],
        'language': value['language'],
        'languages': value['languages'],
        'elimination': value['elimination'],
        'eliminationValueCode': value['eliminationValueCode'],
        'type': CodeListTypeToJSON(value['type']),
        'values': ((value['values'] as Array<any>).map(ValueMapToJSON)),
        'links': ((value['links'] as Array<any>).map(LinkToJSON)),
    };
}

