/* tslint:disable */
/* eslint-disable */
/**
 * PxApi
 * This api lets you do 2 things; Find a table(Navigation) and use a table (Table).  _Table below is added to show how tables can be described in yml._  **Table contains status code this API may return** | Status code    | Description      | Reason                      | | -------        | -----------      | ---------------------       | | 200            | Success          | The endpoint has delivered response for the request                      | | 400            | Bad request      | If the request is not valid | | 403            | Forbidden        | number of cells exceed the API limit | | 404            | Not found        | If the URL in request does not exist | | 429            | Too many request | Requests exceed the API time limit. Large queries should be run in sequence | | 50X            | Internal Server Error | The service might be down | 
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Type of codelist
 * @export
 */
export const CodeListType = {
    Aggregation: 'Aggregation',
    Valueset: 'Valueset'
} as const;
export type CodeListType = typeof CodeListType[keyof typeof CodeListType];


export function instanceOfCodeListType(value: any): boolean {
    for (const key in CodeListType) {
        if (Object.prototype.hasOwnProperty.call(CodeListType, key)) {
            if (CodeListType[key as keyof typeof CodeListType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CodeListTypeFromJSON(json: any): CodeListType {
    return CodeListTypeFromJSONTyped(json, false);
}

export function CodeListTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CodeListType {
    return json as CodeListType;
}

export function CodeListTypeToJSON(value?: CodeListType | null): any {
    return value as any;
}

export function CodeListTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): CodeListType {
    return value as CodeListType;
}

