/* tslint:disable */
/* eslint-disable */
/**
 * PxApi
 * This api lets you do 2 things; Find a table(Navigation) and use a table (Table).  _Table below is added to show how tables can be described in yml._  **Table contains status code this API may return** | Status code    | Description      | Reason                      | | -------        | -----------      | ---------------------       | | 200            | Success          | The endpoint has delivered response for the request                      | | 400            | Bad request      | If the request is not valid | | 403            | Forbidden        | number of cells exceed the API limit | | 404            | Not found        | If the URL in request does not exist | | 429            | Too many request | Requests exceed the API time limit. Large queries should be run in sequence | | 50X            | Internal Server Error | The service might be down | 
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DimensionExtension
 */
export interface DimensionExtension {
    /**
     * A extension object
     * @type {{ [key: string]: string; }}
     * @memberof DimensionExtension
     */
    extension?: { [key: string]: string; };
}

/**
 * Check if a given object implements the DimensionExtension interface.
 */
export function instanceOfDimensionExtension(value: object): value is DimensionExtension {
    return true;
}

export function DimensionExtensionFromJSON(json: any): DimensionExtension {
    return DimensionExtensionFromJSONTyped(json, false);
}

export function DimensionExtensionFromJSONTyped(json: any, ignoreDiscriminator: boolean): DimensionExtension {
    if (json == null) {
        return json;
    }
    return {
        
        'extension': json['extension'] == null ? undefined : json['extension'],
    };
}

export function DimensionExtensionToJSON(json: any): DimensionExtension {
    return DimensionExtensionToJSONTyped(json, false);
}

export function DimensionExtensionToJSONTyped(value?: DimensionExtension | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'extension': value['extension'],
    };
}

