/* tslint:disable */
/* eslint-disable */
/**
 * PxApi
 * This api lets you do 2 things; Find a table(Navigation) and use a table (Table).  _Table below is added to show how tables can be described in yml._  **Table contains status code this API may return** | Status code    | Description      | Reason                      | | -------        | -----------      | ---------------------       | | 200            | Success          | The endpoint has delivered response for the request                      | | 400            | Bad request      | If the request is not valid | | 403            | Forbidden        | number of cells exceed the API limit | | 404            | Not found        | If the URL in request does not exist | | 429            | Too many request | Requests exceed the API time limit. Large queries should be run in sequence | | 50X            | Internal Server Error | The service might be down | 
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FolderContentItemTypeEnum } from './FolderContentItemTypeEnum';
import {
    FolderContentItemTypeEnumFromJSON,
    FolderContentItemTypeEnumFromJSONTyped,
    FolderContentItemTypeEnumToJSON,
    FolderContentItemTypeEnumToJSONTyped,
} from './FolderContentItemTypeEnum';
import type { FolderContentItem } from './FolderContentItem';
import {
    FolderContentItemFromJSON,
    FolderContentItemFromJSONTyped,
    FolderContentItemToJSON,
    FolderContentItemToJSONTyped,
} from './FolderContentItem';

/**
 * Heading item
 * @export
 * @interface Heading
 */
export interface Heading extends FolderContentItem {
}



/**
 * Check if a given object implements the Heading interface.
 */
export function instanceOfHeading(value: object): value is Heading {
    return true;
}

export function HeadingFromJSON(json: any): Heading {
    return HeadingFromJSONTyped(json, false);
}

export function HeadingFromJSONTyped(json: any, ignoreDiscriminator: boolean): Heading {
    return json;
}

export function HeadingToJSON(json: any): Heading {
    return HeadingToJSONTyped(json, false);
}

export function HeadingToJSONTyped(value?: Heading | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

