/* tslint:disable */
/* eslint-disable */
/**
 * PxApi
 * This api lets you do 2 things; Find a table(Navigation) and use a table (Table).  _Table below is added to show how tables can be described in yml._  **Table contains status code this API may return** | Status code    | Description      | Reason                      | | -------        | -----------      | ---------------------       | | 200            | Success          | The endpoint has delivered response for the request                      | | 400            | Bad request      | If the request is not valid | | 403            | Forbidden        | number of cells exceed the API limit | | 404            | Not found        | If the URL in request does not exist | | 429            | Too many request | Requests exceed the API time limit. Large queries should be run in sequence | | 50X            | Internal Server Error | The service might be down | 
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JsonstatCategoryUnitValue
 */
export interface JsonstatCategoryUnitValue {
    /**
     * It is the base unit (person, gram, euro, etc.).
     * @type {string}
     * @memberof JsonstatCategoryUnitValue
     */
    base?: string;
    /**
     * Number of decimals
     * @type {number}
     * @memberof JsonstatCategoryUnitValue
     */
    decimals?: number;
}

/**
 * Check if a given object implements the JsonstatCategoryUnitValue interface.
 */
export function instanceOfJsonstatCategoryUnitValue(value: object): value is JsonstatCategoryUnitValue {
    return true;
}

export function JsonstatCategoryUnitValueFromJSON(json: any): JsonstatCategoryUnitValue {
    return JsonstatCategoryUnitValueFromJSONTyped(json, false);
}

export function JsonstatCategoryUnitValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): JsonstatCategoryUnitValue {
    if (json == null) {
        return json;
    }
    return {
        
        'base': json['base'] == null ? undefined : json['base'],
        'decimals': json['decimals'] == null ? undefined : json['decimals'],
    };
}

export function JsonstatCategoryUnitValueToJSON(json: any): JsonstatCategoryUnitValue {
    return JsonstatCategoryUnitValueToJSONTyped(json, false);
}

export function JsonstatCategoryUnitValueToJSONTyped(value?: JsonstatCategoryUnitValue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'base': value['base'],
        'decimals': value['decimals'],
    };
}

