/* tslint:disable */
/* eslint-disable */
/**
 * PxApi
 * This api lets you do 2 things; Find a table(Navigation) and use a table (Table).  _Table below is added to show how tables can be described in yml._  **Table contains status code this API may return** | Status code    | Description      | Reason                      | | -------        | -----------      | ---------------------       | | 200            | Success          | The endpoint has delivered response for the request                      | | 400            | Bad request      | If the request is not valid | | 403            | Forbidden        | number of cells exceed the API limit | | 404            | Not found        | If the URL in request does not exist | | 429            | Too many request | Requests exceed the API time limit. Large queries should be run in sequence | | 50X            | Internal Server Error | The service might be down | 
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JsonstatLink
 */
export interface JsonstatLink {
    /**
     * 
     * @type {string}
     * @memberof JsonstatLink
     */
    type?: string;
    /**
     * Specification on json-stat.org -> [here](https://json-stat.org/full/#href)
     * @type {string}
     * @memberof JsonstatLink
     */
    href?: string;
}

/**
 * Check if a given object implements the JsonstatLink interface.
 */
export function instanceOfJsonstatLink(value: object): value is JsonstatLink {
    return true;
}

export function JsonstatLinkFromJSON(json: any): JsonstatLink {
    return JsonstatLinkFromJSONTyped(json, false);
}

export function JsonstatLinkFromJSONTyped(json: any, ignoreDiscriminator: boolean): JsonstatLink {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'href': json['href'] == null ? undefined : json['href'],
    };
}

export function JsonstatLinkToJSON(json: any): JsonstatLink {
    return JsonstatLinkToJSONTyped(json, false);
}

export function JsonstatLinkToJSONTyped(value?: JsonstatLink | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'href': value['href'],
    };
}

