/* tslint:disable */
/* eslint-disable */
/**
 * PxApi
 * This api lets you do 2 things; Find a table(Navigation) and use a table (Table).  _Table below is added to show how tables can be described in yml._  **Table contains status code this API may return** | Status code    | Description      | Reason                      | | -------        | -----------      | ---------------------       | | 200            | Success          | The endpoint has delivered response for the request                      | | 400            | Bad request      | If the request is not valid | | 403            | Forbidden        | number of cells exceed the API limit | | 404            | Not found        | If the URL in request does not exist | | 429            | Too many request | Requests exceed the API time limit. Large queries should be run in sequence | | 50X            | Internal Server Error | The service might be down | 
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DimensionExtension } from './DimensionExtension';
import {
    DimensionExtensionFromJSON,
    DimensionExtensionFromJSONTyped,
    DimensionExtensionToJSON,
    DimensionExtensionToJSONTyped,
} from './DimensionExtension';

/**
 * 
 * @export
 * @interface JsonstatExtensionLink
 */
export interface JsonstatExtensionLink {
    /**
     * 
     * @type {Array<DimensionExtension>}
     * @memberof JsonstatExtensionLink
     */
    describedby?: Array<DimensionExtension>;
}

/**
 * Check if a given object implements the JsonstatExtensionLink interface.
 */
export function instanceOfJsonstatExtensionLink(value: object): value is JsonstatExtensionLink {
    return true;
}

export function JsonstatExtensionLinkFromJSON(json: any): JsonstatExtensionLink {
    return JsonstatExtensionLinkFromJSONTyped(json, false);
}

export function JsonstatExtensionLinkFromJSONTyped(json: any, ignoreDiscriminator: boolean): JsonstatExtensionLink {
    if (json == null) {
        return json;
    }
    return {
        
        'describedby': json['describedby'] == null ? undefined : ((json['describedby'] as Array<any>).map(DimensionExtensionFromJSON)),
    };
}

export function JsonstatExtensionLinkToJSON(json: any): JsonstatExtensionLink {
    return JsonstatExtensionLinkToJSONTyped(json, false);
}

export function JsonstatExtensionLinkToJSONTyped(value?: JsonstatExtensionLink | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'describedby': value['describedby'] == null ? undefined : ((value['describedby'] as Array<any>).map(DimensionExtensionToJSON)),
    };
}

