/* tslint:disable */
/* eslint-disable */
/**
 * PxApi
 * This api lets you do 2 things; Find a table(Navigation) and use a table (Table).  _Table below is added to show how tables can be described in yml._  **Table contains status code this API may return** | Status code    | Description      | Reason                      | | -------        | -----------      | ---------------------       | | 200            | Success          | The endpoint has delivered response for the request                      | | 400            | Bad request      | If the request is not valid | | 403            | Forbidden        | number of cells exceed the API limit | | 404            | Not found        | If the URL in request does not exist | | 429            | Too many request | Requests exceed the API time limit. Large queries should be run in sequence | | 50X            | Internal Server Error | The service might be down | 
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KeyValuePair
 */
export interface KeyValuePair {
    /**
     * The key
     * @type {string}
     * @memberof KeyValuePair
     */
    key: string;
    /**
     * The value associated with the key
     * @type {string}
     * @memberof KeyValuePair
     */
    value: string;
}

/**
 * Check if a given object implements the KeyValuePair interface.
 */
export function instanceOfKeyValuePair(value: object): value is KeyValuePair {
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function KeyValuePairFromJSON(json: any): KeyValuePair {
    return KeyValuePairFromJSONTyped(json, false);
}

export function KeyValuePairFromJSONTyped(json: any, ignoreDiscriminator: boolean): KeyValuePair {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
        'value': json['value'],
    };
}

export function KeyValuePairToJSON(json: any): KeyValuePair {
    return KeyValuePairToJSONTyped(json, false);
}

export function KeyValuePairToJSONTyped(value?: KeyValuePair | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'value': value['value'],
    };
}

