/* tslint:disable */
/* eslint-disable */
/**
 * PxApi
 * This api lets you do 2 things; Find a table(Navigation) and use a table (Table).  _Table below is added to show how tables can be described in yml._  **Table contains status code this API may return** | Status code    | Description      | Reason                      | | -------        | -----------      | ---------------------       | | 200            | Success          | The endpoint has delivered response for the request                      | | 400            | Bad request      | If the request is not valid | | 403            | Forbidden        | number of cells exceed the API limit | | 404            | Not found        | If the URL in request does not exist | | 429            | Too many request | Requests exceed the API time limit. Large queries should be run in sequence | | 50X            | Internal Server Error | The service might be down | 
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const OutputFormatType = {
    Px: 'px',
    JsonStat2: 'json-stat2',
    Csv: 'csv',
    Xlsx: 'xlsx',
    Html: 'html',
    JsonPx: 'json-px',
    Parquet: 'parquet'
} as const;
export type OutputFormatType = typeof OutputFormatType[keyof typeof OutputFormatType];


export function instanceOfOutputFormatType(value: any): boolean {
    for (const key in OutputFormatType) {
        if (Object.prototype.hasOwnProperty.call(OutputFormatType, key)) {
            if (OutputFormatType[key as keyof typeof OutputFormatType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function OutputFormatTypeFromJSON(json: any): OutputFormatType {
    return OutputFormatTypeFromJSONTyped(json, false);
}

export function OutputFormatTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): OutputFormatType {
    return json as OutputFormatType;
}

export function OutputFormatTypeToJSON(value?: OutputFormatType | null): any {
    return value as any;
}

export function OutputFormatTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): OutputFormatType {
    return value as OutputFormatType;
}

