/* tslint:disable */
/* eslint-disable */
/**
 * PxApi
 * This api lets you do 2 things; Find a table(Navigation) and use a table (Table).  _Table below is added to show how tables can be described in yml._  **Table contains status code this API may return** | Status code    | Description      | Reason                      | | -------        | -----------      | ---------------------       | | 200            | Success          | The endpoint has delivered response for the request                      | | 400            | Bad request      | If the request is not valid | | 403            | Forbidden        | number of cells exceed the API limit | | 404            | Not found        | If the URL in request does not exist | | 429            | Too many request | Requests exceed the API time limit. Large queries should be run in sequence | | 50X            | Internal Server Error | The service might be down | 
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Indicates if data is in current or fixed prices.
 * @export
 */
export const PriceType = {
    NotApplicable: 'NotApplicable',
    Current: 'Current',
    Fixed: 'Fixed'
} as const;
export type PriceType = typeof PriceType[keyof typeof PriceType];


export function instanceOfPriceType(value: any): boolean {
    for (const key in PriceType) {
        if (Object.prototype.hasOwnProperty.call(PriceType, key)) {
            if (PriceType[key as keyof typeof PriceType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PriceTypeFromJSON(json: any): PriceType {
    return PriceTypeFromJSONTyped(json, false);
}

export function PriceTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PriceType {
    return json as PriceType;
}

export function PriceTypeToJSON(value?: PriceType | null): any {
    return value as any;
}

export function PriceTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): PriceType {
    return value as PriceType;
}

