/* tslint:disable */
/* eslint-disable */
/**
 * PxApi
 * This api lets you do 2 things; Find a table(Navigation) and use a table (Table).  _Table below is added to show how tables can be described in yml._  **Table contains status code this API may return** | Status code    | Description      | Reason                      | | -------        | -----------      | ---------------------       | | 200            | Success          | The endpoint has delivered response for the request                      | | 400            | Bad request      | If the request is not valid | | 403            | Forbidden        | number of cells exceed the API limit | | 404            | Not found        | If the URL in request does not exist | | 429            | Too many request | Requests exceed the API time limit. Large queries should be run in sequence | | 50X            | Internal Server Error | The service might be down | 
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Indicates the time scale for the variable.
 * @export
 */
export const TimeUnit = {
    Annual: 'Annual',
    Quarterly: 'Quarterly',
    Monthly: 'Monthly',
    Weekly: 'Weekly',
    Other: 'Other'
} as const;
export type TimeUnit = typeof TimeUnit[keyof typeof TimeUnit];


export function instanceOfTimeUnit(value: any): boolean {
    for (const key in TimeUnit) {
        if (Object.prototype.hasOwnProperty.call(TimeUnit, key)) {
            if (TimeUnit[key as keyof typeof TimeUnit] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TimeUnitFromJSON(json: any): TimeUnit {
    return TimeUnitFromJSONTyped(json, false);
}

export function TimeUnitFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeUnit {
    return json as TimeUnit;
}

export function TimeUnitToJSON(value?: TimeUnit | null): any {
    return value as any;
}

export function TimeUnitToJSONTyped(value: any, ignoreDiscriminator: boolean): TimeUnit {
    return value as TimeUnit;
}

