/*
 * PxApi
 *
 * This api lets you: Find a table and extract table metadata and data. 
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using PxWeb.Api2.Server.Converters;

namespace PxWeb.Api2.Server.Models
{ 
        /// <summary>
        /// WorkOnly means that data is adjusted e.g. to take into account the number of working days. SesOnly means that data is seasonally adjusted.
        /// </summary>
        /// <value>WorkOnly means that data is adjusted e.g. to take into account the number of working days. SesOnly means that data is seasonally adjusted.</value>
        [TypeConverter(typeof(CustomEnumConverter<Adjustment>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum Adjustment
        {
            
            /// <summary>
            /// Enum NoneEnum for None
            /// </summary>
            [EnumMember(Value = "None")]
            NoneEnum = 1,
            
            /// <summary>
            /// Enum SesOnlyEnum for SesOnly
            /// </summary>
            [EnumMember(Value = "SesOnly")]
            SesOnlyEnum = 2,
            
            /// <summary>
            /// Enum WorkOnlyEnum for WorkOnly
            /// </summary>
            [EnumMember(Value = "WorkOnly")]
            WorkOnlyEnum = 3,
            
            /// <summary>
            /// Enum WorkAndSesEnum for WorkAndSes
            /// </summary>
            [EnumMember(Value = "WorkAndSes")]
            WorkAndSesEnum = 4
        }
}
