/*
 * PxApi
 *
 * This api lets you: Find a table and extract table metadata and data. 
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using PxWeb.Api2.Server.Converters;

namespace PxWeb.Api2.Server.Models
{ 
        /// <summary>
        /// Is always dataset
        /// </summary>
        /// <value>Is always dataset</value>
        [TypeConverter(typeof(CustomEnumConverter<ClassType>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum ClassType
        {
            
            /// <summary>
            /// Enum DatasetEnum for dataset
            /// </summary>
            [EnumMember(Value = "dataset")]
            DatasetEnum = 1
        }
}
