/*
 * PxApi
 *
 * This api lets you: Find a table and extract table metadata and data. 
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using PxWeb.Api2.Server.Converters;

namespace PxWeb.Api2.Server.Models
{ 
        /// <summary>
        /// Type of codelist
        /// </summary>
        /// <value>Type of codelist</value>
        [TypeConverter(typeof(CustomEnumConverter<CodelistType>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum CodelistType
        {
            
            /// <summary>
            /// Enum AggregationEnum for Aggregation
            /// </summary>
            [EnumMember(Value = "Aggregation")]
            AggregationEnum = 1,
            
            /// <summary>
            /// Enum ValuesetEnum for Valueset
            /// </summary>
            [EnumMember(Value = "Valueset")]
            ValuesetEnum = 2
        }
}
