/*
 * PxApi
 *
 * This api lets you: Find a table and extract table metadata and data. 
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using PxWeb.Api2.Server.Converters;

namespace PxWeb.Api2.Server.Models
{ 
        /// <summary>
        /// Indicates if data is stock, flow or average.
        /// </summary>
        /// <value>Indicates if data is stock, flow or average.</value>
        [TypeConverter(typeof(CustomEnumConverter<MeasuringType>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum MeasuringType
        {
            
            /// <summary>
            /// Enum StockEnum for Stock
            /// </summary>
            [EnumMember(Value = "Stock")]
            StockEnum = 1,
            
            /// <summary>
            /// Enum FlowEnum for Flow
            /// </summary>
            [EnumMember(Value = "Flow")]
            FlowEnum = 2,
            
            /// <summary>
            /// Enum AverageEnum for Average
            /// </summary>
            [EnumMember(Value = "Average")]
            AverageEnum = 3,
            
            /// <summary>
            /// Enum OtherEnum for Other
            /// </summary>
            [EnumMember(Value = "Other")]
            OtherEnum = 4
        }
}
