/*
 * PxApi
 *
 * This api lets you: Find a table and extract table metadata and data. 
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using PxWeb.Api2.Server.Converters;

namespace PxWeb.Api2.Server.Models
{ 
    /// <summary>
    /// Holds links for a dimention and or category.
    /// </summary>
    [DataContract]
    public class MetaidDimentionEntry : IEquatable<MetaidDimentionEntry>
    {
        /// <summary>
        /// Array of metaid-link.
        /// </summary>
        /// <value>Array of metaid-link.</value>
        [DataMember(Name="dimension-links", EmitDefaultValue=false)]
        public List<MetaidLink> DimensionLinks { get; set; }

        /// <summary>
        /// Dictionary where key is a category-code and value is a array of metaid-link.
        /// </summary>
        /// <value>Dictionary where key is a category-code and value is a array of metaid-link.</value>
        [DataMember(Name="category-links", EmitDefaultValue=false)]
        public Dictionary<string, List<MetaidLink>> CategoryLinks { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MetaidDimentionEntry {\n");
            sb.Append("  DimensionLinks: ").Append(DimensionLinks).Append("\n");
            sb.Append("  CategoryLinks: ").Append(CategoryLinks).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((MetaidDimentionEntry)obj);
        }

        /// <summary>
        /// Returns true if MetaidDimentionEntry instances are equal
        /// </summary>
        /// <param name="other">Instance of MetaidDimentionEntry to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MetaidDimentionEntry other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    DimensionLinks == other.DimensionLinks ||
                    DimensionLinks != null &&
                    other.DimensionLinks != null &&
                    DimensionLinks.SequenceEqual(other.DimensionLinks)
                ) && 
                (
                    CategoryLinks == other.CategoryLinks ||
                    CategoryLinks != null &&
                    other.CategoryLinks != null &&
                    CategoryLinks.SequenceEqual(other.CategoryLinks)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (DimensionLinks != null)
                    hashCode = hashCode * 59 + DimensionLinks.GetHashCode();
                    if (CategoryLinks != null)
                    hashCode = hashCode * 59 + CategoryLinks.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(MetaidDimentionEntry left, MetaidDimentionEntry right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(MetaidDimentionEntry left, MetaidDimentionEntry right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
