/*
 * PxApi
 *
 * This api lets you do 2 things; Find a table(Navigation) and use a table (Table).  _Table below is added to show how tables can be described in yml._  **Table contains status code this API may return** | Status code    | Description      | Reason                      | | - -- -- --        | - -- -- -- -- --      | - -- -- -- -- -- -- -- -- -- --       | | 200            | Success          | The endpoint has delivered response for the request                      | | 400            | Bad request      | If the request is not valid | | 403            | Forbidden        | number of cells exceed the API limit | | 404            | Not found        | If the URL in request does not exist | | 429            | Too many request | Requests exceed the API time limit. Large queries should be run in sequence | | 50X            | Internal Server Error | The service might be down | 
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using PxWeb.Api2.Server.Converters;

namespace PxWeb.Api2.Server.Models
{ 
        /// <summary>
        /// Parameters for the output format.  * UseCodes: Can not be combined with UseTexts and UseCodesAndTexts. And only applicable for csv, html and xlsx output format. * UseTexts: Can not be combined with UsedCodes and UseCodesAndTexts. And only applicable for csv, html and xlsx output format. * UseCodesAndTexts: Can not be combined with UseCodess and UseTexts. And only applicable for csv, html and xlsx output format. * IncludeTitle: Only applicable for csv, html and xlsx output format. * SeparatorTab: Can not be combined with SeparatorSpace and SeparatorSemicolon. And only applicable for csv output format. * SeparatorSpace: Can not be combined with SeparatorTab and SeparatorSemicolon. And only applicable for csv output format. * SeparatorSemicolon: Can not be combined with SeparatorTab and SeparatorSpace. And only applicable for csv output format. 
        /// </summary>
        /// <value>Parameters for the output format.  * UseCodes: Can not be combined with UseTexts and UseCodesAndTexts. And only applicable for csv, html and xlsx output format. * UseTexts: Can not be combined with UsedCodes and UseCodesAndTexts. And only applicable for csv, html and xlsx output format. * UseCodesAndTexts: Can not be combined with UseCodess and UseTexts. And only applicable for csv, html and xlsx output format. * IncludeTitle: Only applicable for csv, html and xlsx output format. * SeparatorTab: Can not be combined with SeparatorSpace and SeparatorSemicolon. And only applicable for csv output format. * SeparatorSpace: Can not be combined with SeparatorTab and SeparatorSemicolon. And only applicable for csv output format. * SeparatorSemicolon: Can not be combined with SeparatorTab and SeparatorSpace. And only applicable for csv output format. </value>
        [TypeConverter(typeof(CustomEnumConverter<OutputFormatParamType>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum OutputFormatParamType
        {
            
            /// <summary>
            /// Enum UseCodesEnum for UseCodes
            /// </summary>
            [EnumMember(Value = "UseCodes")]
            UseCodesEnum = 1,
            
            /// <summary>
            /// Enum UseTextsEnum for UseTexts
            /// </summary>
            [EnumMember(Value = "UseTexts")]
            UseTextsEnum = 2,
            
            /// <summary>
            /// Enum UseCodesAndTextsEnum for UseCodesAndTexts
            /// </summary>
            [EnumMember(Value = "UseCodesAndTexts")]
            UseCodesAndTextsEnum = 3,
            
            /// <summary>
            /// Enum IncludeTitleEnum for IncludeTitle
            /// </summary>
            [EnumMember(Value = "IncludeTitle")]
            IncludeTitleEnum = 4,
            
            /// <summary>
            /// Enum SeparatorTabEnum for SeparatorTab
            /// </summary>
            [EnumMember(Value = "SeparatorTab")]
            SeparatorTabEnum = 5,
            
            /// <summary>
            /// Enum SeparatorSpaceEnum for SeparatorSpace
            /// </summary>
            [EnumMember(Value = "SeparatorSpace")]
            SeparatorSpaceEnum = 6,
            
            /// <summary>
            /// Enum SeparatorSemicolonEnum for SeparatorSemicolon
            /// </summary>
            [EnumMember(Value = "SeparatorSemicolon")]
            SeparatorSemicolonEnum = 7
        }
}
