/*
 * PxApi
 *
 * This api lets you: Find a table and extract table metadata and data. 
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using PxWeb.Api2.Server.Converters;

namespace PxWeb.Api2.Server.Models
{ 
        /// <summary>
        /// Gets or Sets OutputFormatType
        /// </summary>
        [TypeConverter(typeof(CustomEnumConverter<OutputFormatType>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum OutputFormatType
        {
            
            /// <summary>
            /// Enum PxEnum for px
            /// </summary>
            [EnumMember(Value = "px")]
            PxEnum = 1,
            
            /// <summary>
            /// Enum JsonStat2Enum for json-stat2
            /// </summary>
            [EnumMember(Value = "json-stat2")]
            JsonStat2Enum = 2,
            
            /// <summary>
            /// Enum CsvEnum for csv
            /// </summary>
            [EnumMember(Value = "csv")]
            CsvEnum = 3,
            
            /// <summary>
            /// Enum XlsxEnum for xlsx
            /// </summary>
            [EnumMember(Value = "xlsx")]
            XlsxEnum = 4,
            
            /// <summary>
            /// Enum HtmlEnum for html
            /// </summary>
            [EnumMember(Value = "html")]
            HtmlEnum = 5,
            
            /// <summary>
            /// Enum JsonPxEnum for json-px
            /// </summary>
            [EnumMember(Value = "json-px")]
            JsonPxEnum = 6,
            
            /// <summary>
            /// Enum ParquetEnum for parquet
            /// </summary>
            [EnumMember(Value = "parquet")]
            ParquetEnum = 7
        }
}
