/*
 * PxApi
 *
 * This api lets you: Find a table and extract table metadata and data. 
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using PxWeb.Api2.Server.Converters;

namespace PxWeb.Api2.Server.Models
{ 
        /// <summary>
        /// Indicates if data is in current or fixed prices.
        /// </summary>
        /// <value>Indicates if data is in current or fixed prices.</value>
        [TypeConverter(typeof(CustomEnumConverter<PriceType>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum PriceType
        {
            
            /// <summary>
            /// Enum NotApplicableEnum for NotApplicable
            /// </summary>
            [EnumMember(Value = "NotApplicable")]
            NotApplicableEnum = 1,
            
            /// <summary>
            /// Enum CurrentEnum for Current
            /// </summary>
            [EnumMember(Value = "Current")]
            CurrentEnum = 2,
            
            /// <summary>
            /// Enum FixedEnum for Fixed
            /// </summary>
            [EnumMember(Value = "Fixed")]
            FixedEnum = 3
        }
}
