/*
 * PxApi
 *
 * This api lets you do 2 things; Find a table(Navigation) and use a table (Table).  _Table below is added to show how tables can be described in yml._  **Table contains status code this API may return** | Status code    | Description      | Reason                      | | - -- -- --        | - -- -- -- -- --      | - -- -- -- -- -- -- -- -- -- --       | | 200            | Success          | The endpoint has delivered response for the request                      | | 400            | Bad request      | If the request is not valid | | 403            | Forbidden        | number of cells exceed the API limit | | 404            | Not found        | If the URL in request does not exist | | 429            | Too many request | Requests exceed the API time limit. Large queries should be run in sequence | | 50X            | Internal Server Error | The service might be down | 
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using PxWeb.Api2.Server.Converters;

namespace PxWeb.Api2.Server.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public class RelationLink : IEquatable<RelationLink>
    {
        /// <summary>
        /// Type of relation, like about-statistics
        /// </summary>
        /// <value>Type of relation, like about-statistics</value>
        [DataMember(Name="relation", EmitDefaultValue=false)]
        public string? Relation { get; set; }

        /// <summary>
        /// Source Meta ID for this link
        /// </summary>
        /// <value>Source Meta ID for this link</value>
        [DataMember(Name="metaid", EmitDefaultValue=false)]
        public string? Metaid { get; set; }

        /// <summary>
        /// URL link
        /// </summary>
        /// <value>URL link</value>
        [DataMember(Name="href", EmitDefaultValue=false)]
        public string? Href { get; set; }

        /// <summary>
        /// Label for the link
        /// </summary>
        /// <value>Label for the link</value>
        [DataMember(Name="label", EmitDefaultValue=false)]
        public string? Label { get; set; }

        /// <summary>
        /// Type of the link, like text/html
        /// </summary>
        /// <value>Type of the link, like text/html</value>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public string? Type { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RelationLink {\n");
            sb.Append("  Relation: ").Append(Relation).Append("\n");
            sb.Append("  Metaid: ").Append(Metaid).Append("\n");
            sb.Append("  Href: ").Append(Href).Append("\n");
            sb.Append("  Label: ").Append(Label).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((RelationLink)obj);
        }

        /// <summary>
        /// Returns true if RelationLink instances are equal
        /// </summary>
        /// <param name="other">Instance of RelationLink to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RelationLink other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Relation == other.Relation ||
                    Relation != null &&
                    Relation.Equals(other.Relation)
                ) && 
                (
                    Metaid == other.Metaid ||
                    Metaid != null &&
                    Metaid.Equals(other.Metaid)
                ) && 
                (
                    Href == other.Href ||
                    Href != null &&
                    Href.Equals(other.Href)
                ) && 
                (
                    Label == other.Label ||
                    Label != null &&
                    Label.Equals(other.Label)
                ) && 
                (
                    Type == other.Type ||
                    Type != null &&
                    Type.Equals(other.Type)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Relation != null)
                    hashCode = hashCode * 59 + Relation.GetHashCode();
                    if (Metaid != null)
                    hashCode = hashCode * 59 + Metaid.GetHashCode();
                    if (Href != null)
                    hashCode = hashCode * 59 + Href.GetHashCode();
                    if (Label != null)
                    hashCode = hashCode * 59 + Label.GetHashCode();
                    if (Type != null)
                    hashCode = hashCode * 59 + Type.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(RelationLink left, RelationLink right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(RelationLink left, RelationLink right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
