/*
 * PxApi
 *
 * This api lets you: Find a table and extract table metadata and data. 
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using PxWeb.Api2.Server.Converters;

namespace PxWeb.Api2.Server.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public class SelectionResponse : IEquatable<SelectionResponse>
    {
        /// <summary>
        /// The language code for the language used in this response
        /// </summary>
        /// <value>The language code for the language used in this response</value>
        /* <example>sv</example> */
        [Required]
        [DataMember(Name="language", EmitDefaultValue=false)]
        public string Language { get; set; }

        /// <summary>
        /// Gets or Sets Links
        /// </summary>
        [Required]
        [DataMember(Name="links", EmitDefaultValue=false)]
        public List<Link> Links { get; set; }

        /// <summary>
        /// Gets or Sets Selection
        /// </summary>
        [Required]
        [DataMember(Name="selection", EmitDefaultValue=false)]
        public List<VariableSelection> Selection { get; set; }

        /// <summary>
        /// Gets or Sets Placement
        /// </summary>
        [DataMember(Name="placement", EmitDefaultValue=false)]
        public VariablePlacementType? Placement { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SelectionResponse {\n");
            sb.Append("  Language: ").Append(Language).Append("\n");
            sb.Append("  Links: ").Append(Links).Append("\n");
            sb.Append("  Selection: ").Append(Selection).Append("\n");
            sb.Append("  Placement: ").Append(Placement).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((SelectionResponse)obj);
        }

        /// <summary>
        /// Returns true if SelectionResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of SelectionResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SelectionResponse other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Language == other.Language ||
                    Language != null &&
                    Language.Equals(other.Language)
                ) && 
                (
                    Links == other.Links ||
                    Links != null &&
                    other.Links != null &&
                    Links.SequenceEqual(other.Links)
                ) && 
                (
                    Selection == other.Selection ||
                    Selection != null &&
                    other.Selection != null &&
                    Selection.SequenceEqual(other.Selection)
                ) && 
                (
                    Placement == other.Placement ||
                    Placement != null &&
                    Placement.Equals(other.Placement)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Language != null)
                    hashCode = hashCode * 59 + Language.GetHashCode();
                    if (Links != null)
                    hashCode = hashCode * 59 + Links.GetHashCode();
                    if (Selection != null)
                    hashCode = hashCode * 59 + Selection.GetHashCode();
                    if (Placement != null)
                    hashCode = hashCode * 59 + Placement.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(SelectionResponse left, SelectionResponse right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(SelectionResponse left, SelectionResponse right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
