/*
 * PxApi
 *
 * This api lets you: Find a table and extract table metadata and data. 
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using PxWeb.Api2.Server.Converters;

namespace PxWeb.Api2.Server.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public class ValueMap : IEquatable<ValueMap>
    {
        /// <summary>
        /// The code for the value.
        /// </summary>
        /// <value>The code for the value.</value>
        /* <example>SE22</example> */
        [Required]
        [DataMember(Name="code", EmitDefaultValue=false)]
        public string Code { get; set; }

        /// <summary>
        /// The textual representation for the value
        /// </summary>
        /// <value>The textual representation for the value</value>
        /* <example>Sydsverige</example> */
        [Required]
        [DataMember(Name="label", EmitDefaultValue=false)]
        public string Label { get; set; }

        /// <summary>
        /// An array of codes from the origial codelist for the variable that cand be mapped to this value
        /// </summary>
        /// <value>An array of codes from the origial codelist for the variable that cand be mapped to this value</value>
        /* <example>[&quot;10&quot;, &quot;12&quot;]</example> */
        [Required]
        [DataMember(Name="valueMap", EmitDefaultValue=false)]
        public List<string> VarValueMap { get; set; }

        /// <summary>
        /// Optional notes that are associated with the value
        /// </summary>
        /// <value>Optional notes that are associated with the value</value>
        [DataMember(Name="notes", EmitDefaultValue=false)]
        public List<Note> Notes { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ValueMap {\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  Label: ").Append(Label).Append("\n");
            sb.Append("  VarValueMap: ").Append(VarValueMap).Append("\n");
            sb.Append("  Notes: ").Append(Notes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ValueMap)obj);
        }

        /// <summary>
        /// Returns true if ValueMap instances are equal
        /// </summary>
        /// <param name="other">Instance of ValueMap to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ValueMap other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Code == other.Code ||
                    Code != null &&
                    Code.Equals(other.Code)
                ) && 
                (
                    Label == other.Label ||
                    Label != null &&
                    Label.Equals(other.Label)
                ) && 
                (
                    VarValueMap == other.VarValueMap ||
                    VarValueMap != null &&
                    other.VarValueMap != null &&
                    VarValueMap.SequenceEqual(other.VarValueMap)
                ) && 
                (
                    Notes == other.Notes ||
                    Notes != null &&
                    other.Notes != null &&
                    Notes.SequenceEqual(other.Notes)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Code != null)
                    hashCode = hashCode * 59 + Code.GetHashCode();
                    if (Label != null)
                    hashCode = hashCode * 59 + Label.GetHashCode();
                    if (VarValueMap != null)
                    hashCode = hashCode * 59 + VarValueMap.GetHashCode();
                    if (Notes != null)
                    hashCode = hashCode * 59 + Notes.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ValueMap left, ValueMap right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ValueMap left, ValueMap right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
