/* tslint:disable */
/* eslint-disable */
/**
 * PxApi
 * This api lets you do 2 things; Find a table(Navigation) and use a table (Table).  _Table below is added to show how tables can be described in yml._  **Table contains status code this API may return** | Status code    | Description      | Reason                      | | -------        | -----------      | ---------------------       | | 200            | Success          | The endpoint has delivered response for the request                      | | 400            | Bad request      | If the request is not valid | | 403            | Forbidden        | number of cells exceed the API limit | | 404            | Not found        | If the URL in request does not exist | | 429            | Too many request | Requests exceed the API time limit. Large queries should be run in sequence | | 50X            | Internal Server Error | The service might be down | 
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  FolderResponse,
  Problem,
} from '../models/index';
import {
    FolderResponseFromJSON,
    FolderResponseToJSON,
    ProblemFromJSON,
    ProblemToJSON,
} from '../models/index';

export interface GetNavigationByIdRequest {
    id: string;
    lang?: string | null;
}

export interface GetNavigationRootRequest {
    lang?: string | null;
}

/**
 * 
 */
export class NavigationApi extends runtime.BaseAPI {

    /**
     * Gets Folder by {id}.
     */
    async getNavigationByIdRaw(requestParameters: GetNavigationByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FolderResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getNavigationById().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/navigation/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FolderResponseFromJSON(jsonValue));
    }

    /**
     * Gets Folder by {id}.
     */
    async getNavigationById(requestParameters: GetNavigationByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FolderResponse> {
        const response = await this.getNavigationByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get root Folder.
     */
    async getNavigationRootRaw(requestParameters: GetNavigationRootRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FolderResponse>> {
        const queryParameters: any = {};

        if (requestParameters['lang'] != null) {
            queryParameters['lang'] = requestParameters['lang'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/navigation`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FolderResponseFromJSON(jsonValue));
    }

    /**
     * Get root Folder.
     */
    async getNavigationRoot(requestParameters: GetNavigationRootRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FolderResponse> {
        const response = await this.getNavigationRootRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
