name: Build server library and deploy to nuget
on:
  workflow_dispatch:

jobs:
  generate-aspnetcore-server:
    runs-on: ubuntu-latest
    name: Generate aspnet core server
    
    steps:
      # Checkout your code
      - name: Checkout
        uses: actions/checkout@v2

      # Generate your OpenAPI document (if you don't write it manually)

      # Use the action to generate a server library
      - name: Generate ASPNET Core server
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: aspnetcore
          openapi-file: PxAPI-2.yml
          config-file: aspnetcore-generator-config.yml
          command-args: -o out

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Install minver locally
        run: | 
          dotnet new tool-manifest
          dotnet tool install minver-cli

      - name: Calculate version
        run: echo "version=$(dotnet minver -v e)" >> $GITHUB_ENV

      - name: Restore Nuget
        working-directory: ./out
        run: dotnet restore

      - name: Build library
        working-directory: ./out
        run: dotnet build --configuration Release /p:Version=${{ env.version }} 

      - name: Pack library
        working-directory: ./out
        run: dotnet pack --configuration Release /p:Version=${{ env.version }} --output .
      

            
